---
creation_rules:
- path_regex: kubernetes/.*\.devops\.sops\.ya?ml
  encrypted_regex: "^(data|stringData)$"
  gcp_kms: >- # add link to kms crypto key here, multiple keys possible
    projects/

- path_regex: kubernetes/.*\.devops\.sops\.ya?ml
  unencrypted_regex: "^(kind)$"
  gcp_kms: >- # add link to kms crypto key here, multiple keys possible
    projects/

- path_regex: kubernetes/.*\.devs\.sops\.ya?ml
  encrypted_regex: "^(data|stringData)$"
  gcp_kms: >- # add link to kms crypto key here, multiple keys possible
    projects/

- path_regex: kubernetes/.*\.devs\.sops\.ya?ml
  unencrypted_regex: "^(kind)$"
  gcp_kms: >- # add link to kms crypto key here, multiple keys possible
    projects/
