---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  FLUX_DIR: "{{.PROJECT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/infra/terraform"

includes:
  pre-commit: .taskfiles/pre-commit.yaml
  terraform: .taskfiles/terraform.yaml
